CREATE TABLE Movies (
	id INT(100) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(30) NOT NULL,
	description VARCHAR(300) NOT NULL,
    director VARCHAR(30) NOT NULL,
    writer VARCHAR(30) NOT NULL,
    fact VARCHAR(300) NOT NULL,
    img_url VARCHAR(200) NOT NULL
);